import { FadeIn } from './FadeIn'
import { SectionHeading } from './SectionHeading'
import { StatsCard } from './StatsCard'

const BASE = '/github-stats'

/** GitHub activity images generated by `pnpm stats`. Missing images leave no gap. */
export function GithubSection() {
  return (
    <section>
      <SectionHeading>GitHub Activity</SectionHeading>
      <FadeIn className="mx-auto flex max-w-5xl flex-col items-center gap-8 px-4 py-8">
        <StatsCard
          src={`${BASE}/contrib-3d.svg`}
          alt="3D contribution calendar"
          className="w-full max-w-4xl overflow-hidden rounded-xl border shadow-sm"
        />
        <StatsCard
          src={`${BASE}/snake.svg`}
          alt="Snake eating the contribution calendar"
          className="w-full max-w-4xl"
          framed
        />
        <div className="flex w-full flex-wrap items-center justify-center gap-6">
          <StatsCard src={`${BASE}/stats.svg`} alt="GitHub stats" className="w-full max-w-117" />
          <StatsCard
            src={`${BASE}/top-langs.svg`}
            alt="Most used languages"
            className="w-full max-w-117"
          />
        </div>
        <div className="flex w-full flex-wrap items-stretch justify-center gap-6">
          <StatsCard
            src={`${BASE}/metrics-overview.svg`}
            alt="GitHub profile overview"
            className="w-full max-w-120"
            framed
          />
          <StatsCard
            src={`${BASE}/metrics-isocalendar.svg`}
            alt="Isometric contribution calendar"
            className="w-full max-w-120"
            framed
          />
        </div>
        <StatsCard
          src={`${BASE}/metrics-calendar.svg`}
          alt="Contribution calendar of the last three years"
          className="w-full max-w-120"
          framed
        />
      </FadeIn>
    </section>
  )
}
