/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as FlappybirdRouteImport } from './routes/flappybird'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteLiveabcRouteImport } from './routes/_site.liveabc'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const FlappybirdRoute = FlappybirdRouteImport.update({
  id: '/flappybird',
  path: '/flappybird',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLiveabcRoute = SiteLiveabcRouteImport.update({
  id: '/liveabc',
  path: '/liveabc',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/flappybird': typeof FlappybirdRoute
  '/liveabc': typeof SiteLiveabcRoute
}
export interface FileRoutesByTo {
  '/flappybird': typeof FlappybirdRoute
  '/liveabc': typeof SiteLiveabcRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/flappybird': typeof FlappybirdRoute
  '/_site/liveabc': typeof SiteLiveabcRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flappybird' | '/liveabc'
  fileRoutesByTo: FileRoutesByTo
  to: '/flappybird' | '/liveabc' | '/'
  id: '__root__' | '/_site' | '/flappybird' | '/_site/liveabc' | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  FlappybirdRoute: typeof FlappybirdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flappybird': {
      id: '/flappybird'
      path: '/flappybird'
      fullPath: '/flappybird'
      preLoaderRoute: typeof FlappybirdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/liveabc': {
      id: '/_site/liveabc'
      path: '/liveabc'
      fullPath: '/liveabc'
      preLoaderRoute: typeof SiteLiveabcRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteLiveabcRoute: typeof SiteLiveabcRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteLiveabcRoute: SiteLiveabcRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  FlappybirdRoute: FlappybirdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
